version: '2'

services:
  ipsec:
    image: hwdsl2/ipsec-vpn-server
    environment:
      - VPN_IPSEC_PSK
      - VPN_USER
      - VPN_PASSWORD
    restart: unless-stopped
    ports:
      - 500:500/udp
      - 4500:4500/udp
    volumes:
      - /lib/modules:/lib/modules:ro
    privileged: true
